let a = `hello`;
let b = `owu`;
let c = `com`;
let d = `ua`;
let e =  1;
let f =  10;
let g = -999;
let h = 123;
let j = 3.14;
let k = 2.7;
let l = 16;
let m = true;
let n = false;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(j);
console.log(k);
console.log(l);
console.log(m);
console.log(n);
